#include "idt.h"
#include "cpu.h"
#include "vga.h"
#include "printf.h"
#include "string.h"

#define IDT_ENTRIES 256

typedef struct PACKED {
    uint16_t offset_low;
    uint16_t selector;
    uint8_t  ist;
    uint8_t  type_attr;   /* Present | DPL | Gate type */
    uint16_t offset_mid;
    uint32_t offset_high;
    uint32_t reserved;
} IDTEntry;

typedef struct PACKED {
    uint16_t size;
    uint64_t base;
} IDTPointer;

static IDTEntry  idt[IDT_ENTRIES] ALIGN(8);
static IDTPointer idt_ptr;

/* Table of stub addresses generated by isr_stubs.asm */
extern uint64_t isr_stub_table[IDT_ENTRIES];

/* C-level handlers (NULL = default) */
static ISRHandler handlers[IDT_ENTRIES];

static const char *exception_names[] = {
    "Divide Error",          "Debug",                 "NMI",
    "Breakpoint",            "Overflow",               "Bound Range",
    "Invalid Opcode",        "Device Not Available",   "Double Fault",
    "Coprocessor Overrun",   "Invalid TSS",            "Segment Not Present",
    "Stack-Segment Fault",   "General Protection",     "Page Fault",
    "Reserved",              "x87 FPU Error",          "Alignment Check",
    "Machine Check",         "SIMD FPU Exception",     "Virtualization",
    "Control Protection",
};

static void idt_set_gate(uint8_t vec, uint64_t handler, uint8_t ist, uint8_t dpl)
{
    idt[vec].offset_low  = handler & 0xFFFF;
    idt[vec].selector    = 0x08;        /* kernel code segment */
    idt[vec].ist         = ist & 0x07;
    idt[vec].type_attr   = 0x8E | ((dpl & 3) << 5);  /* Present, Interrupt Gate */
    idt[vec].offset_mid  = (handler >> 16) & 0xFFFF;
    idt[vec].offset_high = (handler >> 32) & 0xFFFFFFFF;
    idt[vec].reserved    = 0;
}

void idt_set_handler(uint8_t vec, ISRHandler fn)
{
    handlers[vec] = fn;
}

/* Install a raw 64-bit handler address, bypassing the generic stubs.
   Used by the scheduler to install sched_timer_stub at vector 32. */
void idt_set_raw_handler(uint8_t vec, uint64_t addr)
{
    idt_set_gate(vec, addr, 0, 0);
}

void isr_handler(Registers *r)
{
    /* Call registered handler if any */
    if (handlers[r->int_no]) {
        handlers[r->int_no](r);
        return;
    }

    /* Default: print info for exceptions */
    if (r->int_no < 32) {
        const char *name = (r->int_no < 22) ? exception_names[r->int_no] : "Reserved";
        kprintf("\n[EXCEPTION #%llu] %s\n", r->int_no, name);
        kprintf("  err=0x%llx  rip=0x%016llx  cs=0x%llx\n",
                r->err_code, r->rip, r->cs);
        kprintf("  rsp=0x%016llx  rflags=0x%llx\n", r->rsp, r->rflags);
        kprintf("  rax=0x%llx rbx=0x%llx rcx=0x%llx rdx=0x%llx\n",
                r->rax, r->rbx, r->rcx, r->rdx);
        kprintf("  HALTING.\n");
        halt_loop();
    }

    /* Spurious/unhandled IRQ — ignore */
}

void idt_init(void)
{
    memset(idt, 0, sizeof(idt));
    memset(handlers, 0, sizeof(handlers));

    for (int i = 0; i < IDT_ENTRIES; i++) {
        idt_set_gate(i, isr_stub_table[i], 0, 0);
    }

    /* Double fault uses IST slot 1 for a separate stack */
    idt_set_gate(8, isr_stub_table[8], 1, 0);

    idt_ptr.size = sizeof(idt) - 1;
    idt_ptr.base = (uint64_t)idt;
    idt_flush(&idt_ptr);
}
